apiVersion: v1
data:
  mapRoles: |
    - groups:
        - system:bootstrappers
        - system:nodes
      rolearn: arn:aws:iam::672636165283:role/eksctl-simple-jwt-api3-nodegroup-n-NodeInstanceRole-iZj7nkJ0suwx
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
        - system:masters
      rolearn: arn:aws:iam::672636165283:role/UdacityFlaskDeployCBKubectlRole
      username: build
kind: ConfigMap
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","data":{"mapRoles":"- groups:\n    - system:bootstrappers\n    - system:nodes\n  rolearn: arn:aws:iam::672636165283:role/eksctl-simple-jwt-api3-nodegroup-n-NodeInstanceRole-iZj7nkJ0suwx\n  username: system:node:{{EC2PrivateDNSName}}\n- groups:\n    - system:masters\n  rolearn: arn:aws:iam::672636165283:role/UdacityFlaskDeployCBKubectlRole\n  username: build\n"},"kind":"ConfigMap","metadata":{"annotations":{},"name":"aws-auth","namespace":"kube-system"}}
  creationTimestamp: "2024-12-23T16:16:48Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "8738"
  uid: 8b4a8ba3-7536-4fb0-bedd-a9c94974fe2d
